"""Puertos de persistencia. El dominio declara lo que necesita; infrastructure lo cumple."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from stou.domain.entities.category import Category
from stou.domain.entities.exam import Exam
from stou.domain.entities.material import Material
from stou.domain.entities.section import Section
from stou.domain.entities.study_session import StudySession
from stou.domain.entities.task import Task
from stou.domain.values import MaterialKind, TaskStatus
from stou.shared.ids import EntityId


class CategoryRepository(Protocol):
    def add(self, category: Category) -> None: ...
    def update(self, category: Category) -> None: ...
    def get(self, category_id: EntityId) -> Category | None: ...
    def list_all(self) -> list[Category]: ...
    def delete(self, category_id: EntityId) -> None: ...
    def has_children(self, category_id: EntityId) -> bool: ...


class MaterialRepository(Protocol):
    def add(self, material: Material) -> None: ...
    def update(self, material: Material) -> None: ...
    def get(self, material_id: EntityId) -> Material | None: ...
    def delete(self, material_id: EntityId) -> None: ...
    def find_by_hash(self, blob_hash: str) -> Material | None: ...
    def list_all(
        self,
        *,
        category_ids: list[EntityId] | None = None,
        kinds: list[MaterialKind] | None = None,
        include_archived: bool = False,
        search: str | None = None,
        limit: int | None = None,
    ) -> list[Material]: ...
    def count(self, *, include_archived: bool = False) -> int: ...


class SectionRepository(Protocol):
    def add(self, section: Section) -> None: ...
    def add_many(self, sections: list[Section]) -> None: ...
    def update(self, section: Section) -> None: ...
    def get(self, section_id: EntityId) -> Section | None: ...
    def delete(self, section_id: EntityId) -> None: ...
    def list_by_material(
        self, material_id: EntityId, *, include_archived: bool = True
    ) -> list[Section]: ...
    def list_by_ids(self, section_ids: list[EntityId]) -> list[Section]: ...
    def list_by_categories(
        self,
        category_ids: list[EntityId],
        *,
        include_archived: bool = False,
        only_unstudied: bool = False,
    ) -> list[Section]: ...


class TaskRepository(Protocol):
    def add(self, task: Task) -> None: ...
    def update(self, task: Task) -> None: ...
    def get(self, task_id: EntityId) -> Task | None: ...
    def delete(self, task_id: EntityId) -> None: ...
    def list_all(
        self,
        *,
        category_ids: list[EntityId] | None = None,
        statuses: list[TaskStatus] | None = None,
        due_from: datetime | None = None,
        due_to: datetime | None = None,
        search: str | None = None,
        limit: int | None = None,
    ) -> list[Task]: ...
    def list_children(self, parent_id: EntityId) -> list[Task]: ...
    def list_by_section(self, section_id: EntityId) -> list[Task]: ...


class StudySessionRepository(Protocol):
    def add(self, session: StudySession) -> None: ...
    def update(self, session: StudySession) -> None: ...
    def get(self, session_id: EntityId) -> StudySession | None: ...
    def delete(self, session_id: EntityId) -> None: ...
    def list_open(self) -> list[StudySession]: ...
    def list_by_task(self, task_id: EntityId) -> list[StudySession]: ...
    def list_between(self, start: datetime, end: datetime) -> list[StudySession]: ...


class ExamRepository(Protocol):
    def add(self, exam: Exam) -> None: ...
    def update(self, exam: Exam) -> None: ...
    def get(self, exam_id: EntityId) -> Exam | None: ...
    def delete(self, exam_id: EntityId) -> None: ...
    def list_all(
        self,
        *,
        category_ids: list[EntityId] | None = None,
        scheduled_from: datetime | None = None,
        scheduled_to: datetime | None = None,
        pending_only: bool = False,
    ) -> list[Exam]: ...
